spring:
  datasource:
    url: jdbc:postgresql://$(PGHOST):$(PGPORT)/java_travel_booker
    username: $(PGUSER)
    password: $(PGPASSWORD)
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
